# Generated by Django 5.1.3 on 2024-11-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="embedding",
            field=models.BinaryField(null=True),
        ),
    ]
