# Generated by Django 5.1.3 on 2024-12-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_uploadedimage_embedding"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UploadedImage",
            new_name="UploadedImageV2",
        ),
    ]
