# Generated by Django 5.1.3 on 2024-12-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_uploadedimage_uploadedimagev2"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UploadedImageV2",
            new_name="UploadedImage",
        ),
    ]
