# Generated by Django 5.1.3 on 2024-12-08 14:06

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_uploadedimage_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="embedding",
            #field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
