# Generated by Django 5.1.3 on 2024-12-17 06:59

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_uploadedimage_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=512, null=True
            ),
        ),
    ]
